CREATE SCHEMA IF NOT EXISTS notas;

CREATE TABLE notas.nota (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante       VARCHAR(2)     NOT NULL,
    serie                  VARCHAR(4)     NOT NULL,
    correlativo            INTEGER        NOT NULL,
    fecha_emision          DATE           NOT NULL,
    hora_emision           TIME           NOT NULL,
    moneda                 VARCHAR(3)     NOT NULL,
    tipo_cambio            NUMERIC(8, 3)  NOT NULL,
    cliente_id             BIGINT,
    cliente_tipo_doc       VARCHAR(1)     NOT NULL,
    cliente_numero_doc     VARCHAR(15)    NOT NULL,
    cliente_nombre         VARCHAR(200)   NOT NULL,
    cliente_direccion      VARCHAR(200),
    ref_tipo               VARCHAR(2)     NOT NULL,
    ref_serie              VARCHAR(4)     NOT NULL,
    ref_correlativo        INTEGER        NOT NULL,
    codigo_motivo          VARCHAR(2)     NOT NULL,
    descripcion_motivo     VARCHAR(250)   NOT NULL,
    gravadas               NUMERIC(12, 2) NOT NULL,
    gravadas_ivap          NUMERIC(12, 2) NOT NULL,
    exoneradas             NUMERIC(12, 2) NOT NULL,
    inafectas              NUMERIC(12, 2) NOT NULL,
    exportacion            NUMERIC(12, 2) NOT NULL,
    gratuitas              NUMERIC(12, 2) NOT NULL,
    descuento_global       NUMERIC(12, 2) NOT NULL,
    factor_descuento       NUMERIC(8, 5)  NOT NULL,
    igv                    NUMERIC(12, 2) NOT NULL,
    ivap                   NUMERIC(12, 2) NOT NULL,
    igv_gratuitas          NUMERIC(12, 2) NOT NULL,
    icbper                 NUMERIC(12, 2) NOT NULL,
    valor_venta            NUMERIC(12, 2) NOT NULL,
    total                  NUMERIC(12, 2) NOT NULL,
    estado_sunat           VARCHAR(20)    NOT NULL,
    observacion            VARCHAR(500),
    stock_aplicado         BOOLEAN        NOT NULL DEFAULT FALSE,
    creado_en              TIMESTAMPTZ    NOT NULL,
    creado_por             VARCHAR(50),
    actualizado_en         TIMESTAMPTZ    NOT NULL,
    actualizado_por        VARCHAR(50),
    CONSTRAINT uk_nota_numero UNIQUE (tipo_comprobante, serie, correlativo),
    CONSTRAINT ck_nota_tipo CHECK (tipo_comprobante IN ('07', '08')),
    CONSTRAINT ck_nota_ref CHECK (ref_tipo IN ('01', '03')),
    CONSTRAINT ck_nota_moneda CHECK (moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_nota_estado CHECK (estado_sunat IN ('PENDIENTE', 'EN_PROCESO', 'ACEPTADO', 'OBSERVADO',
                                                     'RECHAZADO', 'ANULADO'))
);

CREATE INDEX ix_nota_referencia ON notas.nota (ref_tipo, ref_serie, ref_correlativo);
CREATE INDEX ix_nota_fecha ON notas.nota (fecha_emision);

CREATE TABLE notas.linea (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nota_id              BIGINT          NOT NULL REFERENCES notas.nota (id) ON DELETE CASCADE,
    producto_id          BIGINT,
    codigo               VARCHAR(30)     NOT NULL,
    descripcion          VARCHAR(500)    NOT NULL,
    unidad_medida        VARCHAR(5)      NOT NULL,
    cantidad             NUMERIC(12, 3)  NOT NULL,
    afectacion_igv       VARCHAR(2)      NOT NULL,
    precio_unitario      NUMERIC(16, 10) NOT NULL,
    valor_unitario       NUMERIC(16, 10) NOT NULL,
    porcentaje_impuesto  NUMERIC(5, 2)   NOT NULL,
    descuento            NUMERIC(12, 2)  NOT NULL,
    valor_venta          NUMERIC(12, 2)  NOT NULL,
    impuesto             NUMERIC(12, 2)  NOT NULL,
    icbper               NUMERIC(12, 2)  NOT NULL,
    icbper_por_bolsa     NUMERIC(12, 2)  NOT NULL,
    orden                INTEGER         NOT NULL
);

CREATE INDEX ix_linea_nota ON notas.linea (nota_id);
