CREATE SCHEMA IF NOT EXISTS clientes;

-- Un documento por cliente. El tipo es el código del catálogo 06 de SUNAT.
CREATE TABLE clientes.cliente (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento   VARCHAR(1)   NOT NULL,
    numero_documento VARCHAR(15)  NOT NULL,
    nombre           VARCHAR(200) NOT NULL,
    direccion        VARCHAR(200),
    email            VARCHAR(120),
    telefono         VARCHAR(20),
    fecha_nacimiento DATE,
    creado_en        TIMESTAMPTZ  NOT NULL,
    creado_por       VARCHAR(50),
    actualizado_en   TIMESTAMPTZ  NOT NULL,
    actualizado_por  VARCHAR(50),
    CONSTRAINT uk_cliente_documento UNIQUE (tipo_documento, numero_documento),
    CONSTRAINT ck_cliente_tipo_documento CHECK (tipo_documento IN ('0', '1', '4', '6', '7', 'A', 'B', 'C', 'D', 'E')),
    CONSTRAINT ck_cliente_dni CHECK (tipo_documento <> '1' OR numero_documento ~ '^[0-9]{8}$'),
    CONSTRAINT ck_cliente_ruc CHECK (tipo_documento <> '6' OR numero_documento ~ '^[0-9]{11}$')
);

CREATE INDEX ix_cliente_nombre ON clientes.cliente (lower(nombre));
