CREATE SCHEMA IF NOT EXISTS compras;

CREATE TABLE compras.compra (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante     VARCHAR(2)     NOT NULL,
    serie                VARCHAR(20)    NOT NULL,
    correlativo          VARCHAR(20)    NOT NULL,
    fecha_emision        DATE           NOT NULL,
    proveedor_id         BIGINT,
    proveedor_tipo_doc   VARCHAR(1)     NOT NULL,
    proveedor_numero_doc VARCHAR(15)    NOT NULL,
    proveedor_nombre     VARCHAR(200)   NOT NULL,
    moneda               VARCHAR(3)     NOT NULL,
    gravadas             NUMERIC(12, 2) NOT NULL,
    igv                  NUMERIC(12, 2) NOT NULL,
    total                NUMERIC(12, 2) NOT NULL,
    anulada              BOOLEAN        NOT NULL DEFAULT FALSE,
    observacion          VARCHAR(500),
    creado_en            TIMESTAMPTZ    NOT NULL,
    creado_por           VARCHAR(50),
    actualizado_en       TIMESTAMPTZ    NOT NULL,
    actualizado_por      VARCHAR(50),
    CONSTRAINT uk_compra_numero UNIQUE (tipo_comprobante, serie, correlativo)
);

CREATE TABLE compras.linea (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id       BIGINT          NOT NULL REFERENCES compras.compra (id) ON DELETE CASCADE,
    producto_id     BIGINT,
    codigo          VARCHAR(30)     NOT NULL,
    descripcion     VARCHAR(500)    NOT NULL,
    unidad_medida   VARCHAR(5)      NOT NULL,
    cantidad        NUMERIC(12, 3)  NOT NULL,
    precio_unitario NUMERIC(16, 10) NOT NULL,
    valor_venta     NUMERIC(12, 2)  NOT NULL,
    impuesto        NUMERIC(12, 2)  NOT NULL,
    orden           INTEGER         NOT NULL
);
