CREATE SCHEMA IF NOT EXISTS guias;

CREATE TABLE guias.guia (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie                VARCHAR(4)     NOT NULL,
    correlativo          INTEGER        NOT NULL,
    fecha_emision        DATE           NOT NULL,
    cliente_id           BIGINT,
    cliente_tipo_doc     VARCHAR(1)     NOT NULL,
    cliente_numero_doc   VARCHAR(15)    NOT NULL,
    cliente_nombre       VARCHAR(200)   NOT NULL,
    motivo_traslado      VARCHAR(2)     NOT NULL,
    modalidad            VARCHAR(2)     NOT NULL,
    fecha_traslado       DATE           NOT NULL,
    peso_total           NUMERIC(12, 3) NOT NULL,
    bultos               INTEGER        NOT NULL DEFAULT 1,
    ubigeo_partida       VARCHAR(6)     NOT NULL,
    direccion_partida    VARCHAR(200)   NOT NULL,
    ubigeo_llegada       VARCHAR(6)     NOT NULL,
    direccion_llegada    VARCHAR(200)   NOT NULL,
    transportista_doc    VARCHAR(15),
    transportista_nombre VARCHAR(200),
    placa                VARCHAR(10),
    licencia             VARCHAR(20),
    estado_sunat         VARCHAR(20)    NOT NULL,
    ticket               VARCHAR(80),
    observacion          VARCHAR(500),
    creado_en            TIMESTAMPTZ    NOT NULL,
    creado_por           VARCHAR(50),
    actualizado_en       TIMESTAMPTZ    NOT NULL,
    actualizado_por      VARCHAR(50),
    CONSTRAINT uk_guia_numero UNIQUE (serie, correlativo)
);

CREATE TABLE guias.linea (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guia_id       BIGINT         NOT NULL REFERENCES guias.guia (id) ON DELETE CASCADE,
    producto_id   BIGINT,
    codigo        VARCHAR(30)    NOT NULL,
    descripcion   VARCHAR(500)   NOT NULL,
    unidad_medida VARCHAR(5)     NOT NULL,
    cantidad      NUMERIC(12, 3) NOT NULL,
    orden         INTEGER        NOT NULL
);
