-- Series de numeración por tipo de comprobante. El correlativo es el último número usado.
CREATE TABLE empresa.serie (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante VARCHAR(2)  NOT NULL,
    serie            VARCHAR(4)  NOT NULL,
    correlativo      INTEGER     NOT NULL DEFAULT 0,
    activa           BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en        TIMESTAMPTZ NOT NULL,
    creado_por       VARCHAR(50),
    actualizado_en   TIMESTAMPTZ NOT NULL,
    actualizado_por  VARCHAR(50),
    CONSTRAINT uk_serie_tipo_serie UNIQUE (tipo_comprobante, serie),
    CONSTRAINT ck_serie_tipo CHECK (tipo_comprobante IN ('01', '03', '07', '08', '09', 'NV', 'CT')),
    CONSTRAINT ck_serie_formato CHECK (serie ~ '^[A-Z0-9]{4}$'),
    CONSTRAINT ck_serie_correlativo CHECK (correlativo BETWEEN 0 AND 99999999)
);

INSERT INTO empresa.serie (tipo_comprobante, serie, creado_en, creado_por, actualizado_en, actualizado_por)
VALUES ('01', 'F001', now(), 'flyway', now(), 'flyway'),
       ('03', 'B001', now(), 'flyway', now(), 'flyway'),
       ('NV', 'N001', now(), 'flyway', now(), 'flyway'),
       ('07', 'FC01', now(), 'flyway', now(), 'flyway'),
       ('07', 'BC01', now(), 'flyway', now(), 'flyway'),
       ('08', 'FD01', now(), 'flyway', now(), 'flyway'),
       ('08', 'BD01', now(), 'flyway', now(), 'flyway'),
       ('09', 'T001', now(), 'flyway', now(), 'flyway'),
       ('CT', 'C001', now(), 'flyway', now(), 'flyway');
