CREATE SCHEMA IF NOT EXISTS seguridad;

CREATE TABLE seguridad.usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    username        VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    email           VARCHAR(120),
    rol             VARCHAR(20)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_login    TIMESTAMPTZ,
    creado_en       TIMESTAMPTZ  NOT NULL,
    creado_por      VARCHAR(50),
    actualizado_en  TIMESTAMPTZ  NOT NULL,
    actualizado_por VARCHAR(50),
    CONSTRAINT uk_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_username_minusculas CHECK (username = lower(username)),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMINISTRADOR', 'ESPECIAL', 'VENDEDOR'))
);
