CREATE TABLE sunat.lote (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              VARCHAR(20)   NOT NULL,
    serie             VARCHAR(8)    NOT NULL,
    correlativo       INTEGER       NOT NULL,
    fecha_referencia  DATE          NOT NULL,
    fecha_generacion  DATE          NOT NULL,
    estado            VARCHAR(20)   NOT NULL,
    ticket            VARCHAR(50),
    codigo_respuesta  VARCHAR(10),
    mensaje           VARCHAR(1000),
    hash              VARCHAR(100),
    xml_firmado       BYTEA,
    cdr               BYTEA,
    intentos          INTEGER       NOT NULL DEFAULT 0,
    ultimo_envio      TIMESTAMPTZ,
    creado_en         TIMESTAMPTZ   NOT NULL,
    creado_por        VARCHAR(50),
    actualizado_en    TIMESTAMPTZ   NOT NULL,
    actualizado_por   VARCHAR(50),
    CONSTRAINT uk_lote_numero UNIQUE (tipo, serie, correlativo),
    CONSTRAINT ck_lote_tipo CHECK (tipo IN ('RESUMEN_DIARIO', 'COMUNICACION_BAJA')),
    CONSTRAINT ck_lote_estado CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'ACEPTADO', 'OBSERVADO',
                                                'RECHAZADO', 'ANULADO'))
);

CREATE INDEX ix_lote_fecha ON sunat.lote (fecha_generacion);

CREATE TABLE sunat.lote_linea (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id          BIGINT         NOT NULL REFERENCES sunat.lote (id) ON DELETE CASCADE,
    tipo_comprobante VARCHAR(2)     NOT NULL,
    serie            VARCHAR(4)     NOT NULL,
    correlativo      INTEGER        NOT NULL,
    condicion        INTEGER        NOT NULL,
    cliente_tipo     VARCHAR(1),
    cliente_numero   VARCHAR(15),
    moneda           VARCHAR(3),
    gravadas         NUMERIC(12, 2),
    gravadas_ivap    NUMERIC(12, 2),
    exoneradas       NUMERIC(12, 2),
    inafectas        NUMERIC(12, 2),
    exportacion      NUMERIC(12, 2),
    gratuitas        NUMERIC(12, 2),
    descuento_global NUMERIC(12, 2),
    factor_descuento NUMERIC(8, 5),
    igv              NUMERIC(12, 2),
    ivap             NUMERIC(12, 2),
    igv_gratuitas    NUMERIC(12, 2),
    icbper           NUMERIC(12, 2),
    valor_venta      NUMERIC(12, 2),
    total            NUMERIC(12, 2),
    motivo_baja      VARCHAR(250),
    orden            INTEGER        NOT NULL
);

CREATE INDEX ix_lote_linea ON sunat.lote_linea (lote_id);
