CREATE SCHEMA IF NOT EXISTS sunat;

-- Registro de todo comprobante que se informa a SUNAT. "datos" guarda el contenido con el que se genera el XML,
-- para poder regenerarlo si falló la firma; una vez firmado, se reenvía siempre el mismo XML.
CREATE TABLE sunat.documento_electronico (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante VARCHAR(2)    NOT NULL,
    serie            VARCHAR(4)    NOT NULL,
    correlativo      INTEGER       NOT NULL,
    fecha_emision    DATE          NOT NULL,
    estado           VARCHAR(20)   NOT NULL,
    codigo_respuesta VARCHAR(10),
    mensaje          VARCHAR(1000),
    observaciones    VARCHAR(4000),
    hash             VARCHAR(100),
    datos            JSONB         NOT NULL,
    xml_firmado      BYTEA,
    cdr              BYTEA,
    intentos         INTEGER       NOT NULL DEFAULT 0,
    ultimo_envio     TIMESTAMPTZ,
    version          BIGINT        NOT NULL DEFAULT 0,
    creado_en        TIMESTAMPTZ   NOT NULL,
    creado_por       VARCHAR(50),
    actualizado_en   TIMESTAMPTZ   NOT NULL,
    actualizado_por  VARCHAR(50),
    CONSTRAINT uk_documento_electronico UNIQUE (tipo_comprobante, serie, correlativo),
    CONSTRAINT ck_documento_estado CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'ACEPTADO', 'OBSERVADO',
                                                     'RECHAZADO', 'ANULADO'))
);

CREATE INDEX ix_documento_electronico_estado ON sunat.documento_electronico (estado, fecha_emision);
CREATE INDEX ix_documento_electronico_fecha ON sunat.documento_electronico (fecha_emision);
