CREATE SCHEMA IF NOT EXISTS cotizaciones;

CREATE TABLE cotizaciones.cotizacion (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serie              VARCHAR(4)     NOT NULL,
    correlativo        INTEGER        NOT NULL,
    fecha_emision      DATE           NOT NULL,
    cliente_id         BIGINT,
    cliente_tipo_doc   VARCHAR(1)     NOT NULL,
    cliente_numero_doc VARCHAR(15)    NOT NULL,
    cliente_nombre     VARCHAR(200)   NOT NULL,
    moneda             VARCHAR(3)     NOT NULL,
    gravadas           NUMERIC(12, 2) NOT NULL,
    igv                NUMERIC(12, 2) NOT NULL,
    total              NUMERIC(12, 2) NOT NULL,
    observacion        VARCHAR(500),
    creado_en          TIMESTAMPTZ    NOT NULL,
    creado_por         VARCHAR(50),
    actualizado_en     TIMESTAMPTZ    NOT NULL,
    actualizado_por    VARCHAR(50),
    CONSTRAINT uk_cotizacion_numero UNIQUE (serie, correlativo)
);

CREATE TABLE cotizaciones.linea (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id   BIGINT          NOT NULL REFERENCES cotizaciones.cotizacion (id) ON DELETE CASCADE,
    producto_id     BIGINT,
    codigo          VARCHAR(30)     NOT NULL,
    descripcion     VARCHAR(500)    NOT NULL,
    unidad_medida   VARCHAR(5)      NOT NULL,
    cantidad        NUMERIC(12, 3)  NOT NULL,
    precio_unitario NUMERIC(16, 10) NOT NULL,
    valor_venta     NUMERIC(12, 2)  NOT NULL,
    impuesto        NUMERIC(12, 2)  NOT NULL,
    orden           INTEGER         NOT NULL
);
