CREATE SCHEMA IF NOT EXISTS ventas;

CREATE TABLE ventas.venta (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_comprobante     VARCHAR(2)     NOT NULL,
    serie                VARCHAR(4)     NOT NULL,
    correlativo          INTEGER        NOT NULL,
    fecha_emision        DATE           NOT NULL,
    hora_emision         TIME           NOT NULL,
    fecha_vencimiento    DATE,
    moneda               VARCHAR(3)     NOT NULL,
    tipo_cambio          NUMERIC(8, 3)  NOT NULL,
    cliente_id           BIGINT,
    cliente_tipo_doc     VARCHAR(1)     NOT NULL,
    cliente_numero_doc   VARCHAR(15)    NOT NULL,
    cliente_nombre       VARCHAR(200)   NOT NULL,
    cliente_direccion    VARCHAR(200),
    gravadas             NUMERIC(12, 2) NOT NULL,
    gravadas_ivap        NUMERIC(12, 2) NOT NULL,
    exoneradas           NUMERIC(12, 2) NOT NULL,
    inafectas            NUMERIC(12, 2) NOT NULL,
    exportacion          NUMERIC(12, 2) NOT NULL,
    gratuitas            NUMERIC(12, 2) NOT NULL,
    descuento_global     NUMERIC(12, 2) NOT NULL,
    factor_descuento     NUMERIC(8, 5)  NOT NULL,
    igv                  NUMERIC(12, 2) NOT NULL,
    ivap                 NUMERIC(12, 2) NOT NULL,
    igv_gratuitas        NUMERIC(12, 2) NOT NULL,
    icbper               NUMERIC(12, 2) NOT NULL,
    valor_venta          NUMERIC(12, 2) NOT NULL,
    total                NUMERIC(12, 2) NOT NULL,
    forma_pago           VARCHAR(10)    NOT NULL,
    bienes_selva         BOOLEAN        NOT NULL DEFAULT FALSE,
    servicios_selva      BOOLEAN        NOT NULL DEFAULT FALSE,
    estado_sunat         VARCHAR(20)    NOT NULL,
    observacion          VARCHAR(500),
    stock_devuelto       BOOLEAN        NOT NULL DEFAULT FALSE,
    creado_en            TIMESTAMPTZ    NOT NULL,
    creado_por           VARCHAR(50),
    actualizado_en       TIMESTAMPTZ    NOT NULL,
    actualizado_por      VARCHAR(50),
    CONSTRAINT uk_venta_numero UNIQUE (tipo_comprobante, serie, correlativo),
    CONSTRAINT ck_venta_tipo CHECK (tipo_comprobante IN ('01', '03', 'NV')),
    CONSTRAINT ck_venta_moneda CHECK (moneda IN ('PEN', 'USD')),
    CONSTRAINT ck_venta_forma_pago CHECK (forma_pago IN ('CONTADO', 'CREDITO')),
    CONSTRAINT ck_venta_estado CHECK (estado_sunat IN ('PENDIENTE', 'EN_PROCESO', 'ACEPTADO', 'OBSERVADO',
                                                       'RECHAZADO', 'ANULADO', 'NO_APLICA'))
);

CREATE INDEX ix_venta_fecha ON ventas.venta (fecha_emision);
CREATE INDEX ix_venta_cliente ON ventas.venta (cliente_numero_doc);
CREATE INDEX ix_venta_tipo_fecha ON ventas.venta (tipo_comprobante, fecha_emision);

CREATE TABLE ventas.linea (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id             BIGINT         NOT NULL REFERENCES ventas.venta (id) ON DELETE CASCADE,
    producto_id          BIGINT,
    codigo               VARCHAR(30)    NOT NULL,
    descripcion          VARCHAR(500)   NOT NULL,
    unidad_medida        VARCHAR(5)     NOT NULL,
    cantidad             NUMERIC(12, 3) NOT NULL,
    afectacion_igv       VARCHAR(2)     NOT NULL,
    precio_unitario      NUMERIC(16, 10) NOT NULL,
    valor_unitario       NUMERIC(16, 10) NOT NULL,
    porcentaje_impuesto  NUMERIC(5, 2)  NOT NULL,
    descuento            NUMERIC(12, 2) NOT NULL,
    valor_venta          NUMERIC(12, 2) NOT NULL,
    impuesto             NUMERIC(12, 2) NOT NULL,
    icbper               NUMERIC(12, 2) NOT NULL,
    icbper_por_bolsa     NUMERIC(12, 2) NOT NULL,
    orden                INTEGER        NOT NULL
);

CREATE INDEX ix_linea_venta ON ventas.linea (venta_id);

CREATE TABLE ventas.cuota (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id    BIGINT         NOT NULL REFERENCES ventas.venta (id) ON DELETE CASCADE,
    numero      INTEGER        NOT NULL,
    fecha_pago  DATE           NOT NULL,
    monto       NUMERIC(12, 2) NOT NULL,
    CONSTRAINT uk_cuota_venta_numero UNIQUE (venta_id, numero)
);
